name: Semantic Release

# Run on every push to the main branch, if the user is not semantic-release-bot or nfh-bot
on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    if: github.actor != 'semantic-release-bot' && github.actor != 'nfh-bot'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GH_SSH_KEY }}

      - name: Install dependencies
        run: yarn install

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: false
          working_directory: apps/expo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
